#!/bin/sh
set -ex

pip install pytest pytest-cov
cd /usr/local/share/jaqalpaq
pytest --cov=/usr/local/lib/python${PYTHON_VERSION}/site-packages/jaqalpaq \
       --cov-branch --cov-report=html:/htmlcov
